name: Python CI

on:
  push:
    branches:
      - main  # Replace with your branch name or leave it as 'main' if that's your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run Python script
      run: python3 /Users/ayanjitdutta/git_file/pro1/script.py  # Replace with the path to your Python script

